# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from aep.job.v1 import service_pb2 as aep_dot_job_dot_v1_dot_service__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in aep/job/v1/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class JobServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateJob = channel.unary_unary(
                '/aep.job.v1.JobService/CreateJob',
                request_serializer=aep_dot_job_dot_v1_dot_service__pb2.CreateJobRequest.SerializeToString,
                response_deserializer=aep_dot_job_dot_v1_dot_service__pb2.CreateJobResponse.FromString,
                _registered_method=True)
        self.GetJob = channel.unary_unary(
                '/aep.job.v1.JobService/GetJob',
                request_serializer=aep_dot_job_dot_v1_dot_service__pb2.GetJobRequest.SerializeToString,
                response_deserializer=aep_dot_job_dot_v1_dot_service__pb2.GetJobResponse.FromString,
                _registered_method=True)
        self.UpdateJob = channel.unary_unary(
                '/aep.job.v1.JobService/UpdateJob',
                request_serializer=aep_dot_job_dot_v1_dot_service__pb2.UpdateJobRequest.SerializeToString,
                response_deserializer=aep_dot_job_dot_v1_dot_service__pb2.UpdateJobResponse.FromString,
                _registered_method=True)
        self.RetryJob = channel.unary_unary(
                '/aep.job.v1.JobService/RetryJob',
                request_serializer=aep_dot_job_dot_v1_dot_service__pb2.RetryJobRequest.SerializeToString,
                response_deserializer=aep_dot_job_dot_v1_dot_service__pb2.RetryJobResponse.FromString,
                _registered_method=True)


class JobServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetryJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JobServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateJob,
                    request_deserializer=aep_dot_job_dot_v1_dot_service__pb2.CreateJobRequest.FromString,
                    response_serializer=aep_dot_job_dot_v1_dot_service__pb2.CreateJobResponse.SerializeToString,
            ),
            'GetJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJob,
                    request_deserializer=aep_dot_job_dot_v1_dot_service__pb2.GetJobRequest.FromString,
                    response_serializer=aep_dot_job_dot_v1_dot_service__pb2.GetJobResponse.SerializeToString,
            ),
            'UpdateJob': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateJob,
                    request_deserializer=aep_dot_job_dot_v1_dot_service__pb2.UpdateJobRequest.FromString,
                    response_serializer=aep_dot_job_dot_v1_dot_service__pb2.UpdateJobResponse.SerializeToString,
            ),
            'RetryJob': grpc.unary_unary_rpc_method_handler(
                    servicer.RetryJob,
                    request_deserializer=aep_dot_job_dot_v1_dot_service__pb2.RetryJobRequest.FromString,
                    response_serializer=aep_dot_job_dot_v1_dot_service__pb2.RetryJobResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aep.job.v1.JobService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aep.job.v1.JobService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JobService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aep.job.v1.JobService/CreateJob',
            aep_dot_job_dot_v1_dot_service__pb2.CreateJobRequest.SerializeToString,
            aep_dot_job_dot_v1_dot_service__pb2.CreateJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aep.job.v1.JobService/GetJob',
            aep_dot_job_dot_v1_dot_service__pb2.GetJobRequest.SerializeToString,
            aep_dot_job_dot_v1_dot_service__pb2.GetJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aep.job.v1.JobService/UpdateJob',
            aep_dot_job_dot_v1_dot_service__pb2.UpdateJobRequest.SerializeToString,
            aep_dot_job_dot_v1_dot_service__pb2.UpdateJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetryJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aep.job.v1.JobService/RetryJob',
            aep_dot_job_dot_v1_dot_service__pb2.RetryJobRequest.SerializeToString,
            aep_dot_job_dot_v1_dot_service__pb2.RetryJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
