# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from aep.gateway.v1 import service_pb2 as aep_dot_gateway_dot_v1_dot_service__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in aep/gateway/v1/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GatewayServiceStub:
    """The only path to LLMs in the platform: input guardrails, then a forward
    to the single configured model. Shape mirrors llm-model-service's
    ChatRequest/ChatResponse (model_config + messages + token_usage), plus a
    minimal single-function-call form of tool calling: the caller passes tool
    schemas, the model may answer with tool_calls, the caller executes them
    (e.g. via mcp_svc) and feeds the results back as role="tool" messages.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.unary_unary(
                '/aep.gateway.v1.GatewayService/Chat',
                request_serializer=aep_dot_gateway_dot_v1_dot_service__pb2.ChatRequest.SerializeToString,
                response_deserializer=aep_dot_gateway_dot_v1_dot_service__pb2.ChatResponse.FromString,
                _registered_method=True)


class GatewayServiceServicer:
    """The only path to LLMs in the platform: input guardrails, then a forward
    to the single configured model. Shape mirrors llm-model-service's
    ChatRequest/ChatResponse (model_config + messages + token_usage), plus a
    minimal single-function-call form of tool calling: the caller passes tool
    schemas, the model may answer with tool_calls, the caller executes them
    (e.g. via mcp_svc) and feeds the results back as role="tool" messages.
    """

    def Chat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=aep_dot_gateway_dot_v1_dot_service__pb2.ChatRequest.FromString,
                    response_serializer=aep_dot_gateway_dot_v1_dot_service__pb2.ChatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aep.gateway.v1.GatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aep.gateway.v1.GatewayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GatewayService:
    """The only path to LLMs in the platform: input guardrails, then a forward
    to the single configured model. Shape mirrors llm-model-service's
    ChatRequest/ChatResponse (model_config + messages + token_usage), plus a
    minimal single-function-call form of tool calling: the caller passes tool
    schemas, the model may answer with tool_calls, the caller executes them
    (e.g. via mcp_svc) and feeds the results back as role="tool" messages.
    """

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aep.gateway.v1.GatewayService/Chat',
            aep_dot_gateway_dot_v1_dot_service__pb2.ChatRequest.SerializeToString,
            aep_dot_gateway_dot_v1_dot_service__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
