# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aep/gateway/v1/service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'aep/gateway/v1/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61\x65p/gateway/v1/service.proto\x12\x0e\x61\x65p.gateway.v1\"\xba\x01\n\x0b\x43hatRequest\x12\x31\n\x0cmodel_config\x18\x01 \x01(\x0b\x32\x1b.aep.gateway.v1.ModelConfig\x12)\n\x08messages\x18\x02 \x03(\x0b\x32\x17.aep.gateway.v1.Message\x12#\n\x05tools\x18\x03 \x03(\x0b\x32\x14.aep.gateway.v1.Tool\x12\x18\n\x0btool_choice\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\x0e\n\x0c_tool_choice\"_\n\x0bModelConfig\x12\x18\n\x0btemperature\x18\x01 \x01(\x02H\x00\x88\x01\x01\x12\x17\n\nmax_tokens\x18\x02 \x01(\x05H\x01\x88\x01\x01\x42\x0e\n\x0c_temperatureB\r\n\x0b_max_tokens\"=\n\x04Tool\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x12\n\nparameters\x18\x03 \x01(\t\"7\n\x08ToolCall\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\targuments\x18\x03 \x01(\t\"\x82\x01\n\x07Message\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12,\n\ntool_calls\x18\x03 \x03(\x0b\x32\x18.aep.gateway.v1.ToolCall\x12\x19\n\x0ctool_call_id\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\x0f\n\r_tool_call_id\"\xae\x01\n\x0c\x43hatResponse\x12(\n\x07message\x18\x01 \x01(\x0b\x32\x17.aep.gateway.v1.Message\x12/\n\x0btoken_usage\x18\x02 \x01(\x0b\x32\x1a.aep.gateway.v1.TokenUsage\x12\x15\n\rfinish_reason\x18\x03 \x01(\t\x12,\n\ntool_calls\x18\x04 \x03(\x0b\x32\x18.aep.gateway.v1.ToolCall\"T\n\nTokenUsage\x12\x15\n\rprompt_tokens\x18\x01 \x01(\x03\x12\x19\n\x11\x63ompletion_tokens\x18\x02 \x01(\x03\x12\x14\n\x0ctotal_tokens\x18\x03 \x01(\x03\x32S\n\x0eGatewayService\x12\x41\n\x04\x43hat\x12\x1b.aep.gateway.v1.ChatRequest\x1a\x1c.aep.gateway.v1.ChatResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aep.gateway.v1.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATREQUEST']._serialized_start=49
  _globals['_CHATREQUEST']._serialized_end=235
  _globals['_MODELCONFIG']._serialized_start=237
  _globals['_MODELCONFIG']._serialized_end=332
  _globals['_TOOL']._serialized_start=334
  _globals['_TOOL']._serialized_end=395
  _globals['_TOOLCALL']._serialized_start=397
  _globals['_TOOLCALL']._serialized_end=452
  _globals['_MESSAGE']._serialized_start=455
  _globals['_MESSAGE']._serialized_end=585
  _globals['_CHATRESPONSE']._serialized_start=588
  _globals['_CHATRESPONSE']._serialized_end=762
  _globals['_TOKENUSAGE']._serialized_start=764
  _globals['_TOKENUSAGE']._serialized_end=848
  _globals['_GATEWAYSERVICE']._serialized_start=850
  _globals['_GATEWAYSERVICE']._serialized_end=933
# @@protoc_insertion_point(module_scope)
