# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from aep.agent_execution.v1 import service_pb2 as aep_dot_agent__execution_dot_v1_dot_service__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in aep/agent_execution/v1/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentExecutionServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTool = channel.unary_unary(
                '/aep.agent_execution.v1.AgentExecutionService/CreateTool',
                request_serializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.CreateToolRequest.SerializeToString,
                response_deserializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.CreateToolResponse.FromString,
                _registered_method=True)
        self.GetTool = channel.unary_unary(
                '/aep.agent_execution.v1.AgentExecutionService/GetTool',
                request_serializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.GetToolRequest.SerializeToString,
                response_deserializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.GetToolResponse.FromString,
                _registered_method=True)
        self.UpdateTool = channel.unary_unary(
                '/aep.agent_execution.v1.AgentExecutionService/UpdateTool',
                request_serializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.UpdateToolRequest.SerializeToString,
                response_deserializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.UpdateToolResponse.FromString,
                _registered_method=True)
        self.DeleteTool = channel.unary_unary(
                '/aep.agent_execution.v1.AgentExecutionService/DeleteTool',
                request_serializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.DeleteToolRequest.SerializeToString,
                response_deserializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.DeleteToolResponse.FromString,
                _registered_method=True)
        self.CreateAgent = channel.unary_unary(
                '/aep.agent_execution.v1.AgentExecutionService/CreateAgent',
                request_serializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.CreateAgentRequest.SerializeToString,
                response_deserializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.CreateAgentResponse.FromString,
                _registered_method=True)
        self.GetAgent = channel.unary_unary(
                '/aep.agent_execution.v1.AgentExecutionService/GetAgent',
                request_serializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.GetAgentRequest.SerializeToString,
                response_deserializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.GetAgentResponse.FromString,
                _registered_method=True)
        self.UpdateAgent = channel.unary_unary(
                '/aep.agent_execution.v1.AgentExecutionService/UpdateAgent',
                request_serializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.UpdateAgentRequest.SerializeToString,
                response_deserializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.UpdateAgentResponse.FromString,
                _registered_method=True)
        self.DeleteAgent = channel.unary_unary(
                '/aep.agent_execution.v1.AgentExecutionService/DeleteAgent',
                request_serializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.DeleteAgentRequest.SerializeToString,
                response_deserializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.DeleteAgentResponse.FromString,
                _registered_method=True)
        self.CreateTask = channel.unary_unary(
                '/aep.agent_execution.v1.AgentExecutionService/CreateTask',
                request_serializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.CreateTaskRequest.SerializeToString,
                response_deserializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.CreateTaskResponse.FromString,
                _registered_method=True)
        self.GetTask = channel.unary_unary(
                '/aep.agent_execution.v1.AgentExecutionService/GetTask',
                request_serializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.GetTaskRequest.SerializeToString,
                response_deserializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.GetTaskResponse.FromString,
                _registered_method=True)
        self.ApproveTask = channel.unary_unary(
                '/aep.agent_execution.v1.AgentExecutionService/ApproveTask',
                request_serializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.ApproveTaskRequest.SerializeToString,
                response_deserializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.ApproveTaskResponse.FromString,
                _registered_method=True)
        self.RetryTask = channel.unary_unary(
                '/aep.agent_execution.v1.AgentExecutionService/RetryTask',
                request_serializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.RetryTaskRequest.SerializeToString,
                response_deserializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.RetryTaskResponse.FromString,
                _registered_method=True)


class AgentExecutionServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApproveTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetryTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentExecutionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTool': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTool,
                    request_deserializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.CreateToolRequest.FromString,
                    response_serializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.CreateToolResponse.SerializeToString,
            ),
            'GetTool': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTool,
                    request_deserializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.GetToolRequest.FromString,
                    response_serializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.GetToolResponse.SerializeToString,
            ),
            'UpdateTool': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTool,
                    request_deserializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.UpdateToolRequest.FromString,
                    response_serializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.UpdateToolResponse.SerializeToString,
            ),
            'DeleteTool': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTool,
                    request_deserializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.DeleteToolRequest.FromString,
                    response_serializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.DeleteToolResponse.SerializeToString,
            ),
            'CreateAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAgent,
                    request_deserializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.CreateAgentRequest.FromString,
                    response_serializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.CreateAgentResponse.SerializeToString,
            ),
            'GetAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgent,
                    request_deserializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.GetAgentRequest.FromString,
                    response_serializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.GetAgentResponse.SerializeToString,
            ),
            'UpdateAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAgent,
                    request_deserializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.UpdateAgentRequest.FromString,
                    response_serializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.UpdateAgentResponse.SerializeToString,
            ),
            'DeleteAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAgent,
                    request_deserializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.DeleteAgentRequest.FromString,
                    response_serializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.DeleteAgentResponse.SerializeToString,
            ),
            'CreateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTask,
                    request_deserializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.CreateTaskRequest.FromString,
                    response_serializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.CreateTaskResponse.SerializeToString,
            ),
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.GetTaskRequest.FromString,
                    response_serializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.GetTaskResponse.SerializeToString,
            ),
            'ApproveTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ApproveTask,
                    request_deserializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.ApproveTaskRequest.FromString,
                    response_serializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.ApproveTaskResponse.SerializeToString,
            ),
            'RetryTask': grpc.unary_unary_rpc_method_handler(
                    servicer.RetryTask,
                    request_deserializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.RetryTaskRequest.FromString,
                    response_serializer=aep_dot_agent__execution_dot_v1_dot_service__pb2.RetryTaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aep.agent_execution.v1.AgentExecutionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aep.agent_execution.v1.AgentExecutionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentExecutionService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aep.agent_execution.v1.AgentExecutionService/CreateTool',
            aep_dot_agent__execution_dot_v1_dot_service__pb2.CreateToolRequest.SerializeToString,
            aep_dot_agent__execution_dot_v1_dot_service__pb2.CreateToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aep.agent_execution.v1.AgentExecutionService/GetTool',
            aep_dot_agent__execution_dot_v1_dot_service__pb2.GetToolRequest.SerializeToString,
            aep_dot_agent__execution_dot_v1_dot_service__pb2.GetToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aep.agent_execution.v1.AgentExecutionService/UpdateTool',
            aep_dot_agent__execution_dot_v1_dot_service__pb2.UpdateToolRequest.SerializeToString,
            aep_dot_agent__execution_dot_v1_dot_service__pb2.UpdateToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aep.agent_execution.v1.AgentExecutionService/DeleteTool',
            aep_dot_agent__execution_dot_v1_dot_service__pb2.DeleteToolRequest.SerializeToString,
            aep_dot_agent__execution_dot_v1_dot_service__pb2.DeleteToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aep.agent_execution.v1.AgentExecutionService/CreateAgent',
            aep_dot_agent__execution_dot_v1_dot_service__pb2.CreateAgentRequest.SerializeToString,
            aep_dot_agent__execution_dot_v1_dot_service__pb2.CreateAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aep.agent_execution.v1.AgentExecutionService/GetAgent',
            aep_dot_agent__execution_dot_v1_dot_service__pb2.GetAgentRequest.SerializeToString,
            aep_dot_agent__execution_dot_v1_dot_service__pb2.GetAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aep.agent_execution.v1.AgentExecutionService/UpdateAgent',
            aep_dot_agent__execution_dot_v1_dot_service__pb2.UpdateAgentRequest.SerializeToString,
            aep_dot_agent__execution_dot_v1_dot_service__pb2.UpdateAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aep.agent_execution.v1.AgentExecutionService/DeleteAgent',
            aep_dot_agent__execution_dot_v1_dot_service__pb2.DeleteAgentRequest.SerializeToString,
            aep_dot_agent__execution_dot_v1_dot_service__pb2.DeleteAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aep.agent_execution.v1.AgentExecutionService/CreateTask',
            aep_dot_agent__execution_dot_v1_dot_service__pb2.CreateTaskRequest.SerializeToString,
            aep_dot_agent__execution_dot_v1_dot_service__pb2.CreateTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aep.agent_execution.v1.AgentExecutionService/GetTask',
            aep_dot_agent__execution_dot_v1_dot_service__pb2.GetTaskRequest.SerializeToString,
            aep_dot_agent__execution_dot_v1_dot_service__pb2.GetTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApproveTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aep.agent_execution.v1.AgentExecutionService/ApproveTask',
            aep_dot_agent__execution_dot_v1_dot_service__pb2.ApproveTaskRequest.SerializeToString,
            aep_dot_agent__execution_dot_v1_dot_service__pb2.ApproveTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetryTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aep.agent_execution.v1.AgentExecutionService/RetryTask',
            aep_dot_agent__execution_dot_v1_dot_service__pb2.RetryTaskRequest.SerializeToString,
            aep_dot_agent__execution_dot_v1_dot_service__pb2.RetryTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
